//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("HTTP Client")]
[assembly: AssemblyCompany("Illallangi Enterprises")]
[assembly: AssemblyProduct("HTTP Client")]
[assembly: AssemblyCopyright("Copyright © Illallangi Enterprises 2013")]
[assembly: ComVisible(false)]
[assembly: AssemblyInformationalVersion("Debug Build")]
[assembly: Guid("01635a92-4a4c-4578-ba8e-a4d7278ab433")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]


